name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - 'v*'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update and upgrade apt packages
      run: |
        sudo apt update

    - name: Install required apt packages
      run: |
        sudo apt install -y python3-pyqt5
        sudo apt install -y pyqt5-dev-tools
        sudo apt install -y qttools5-dev-tools

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run action.py for English UI
      run: python action.py en

    - name: Run action.py for Japanese UI
      run: python action.py ja

    - name: Rename builded_en.py to playblast_ffmpeg_en.py
      run: mv builded_en.py playblast_ffmpeg_en.py

    - name: Rename builded_ja.py to playblast_ffmpeg_ja.py
      run: mv builded_ja.py playblast_ffmpeg_ja.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playblast_ffmpeg_en
        path: playblast_ffmpeg_en.py
        retention-days: 5

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playblast_ffmpeg_ja
        path: playblast_ffmpeg_ja.py
        retention-days: 5

    - name: Comment PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Scripts Generated.\n\n[open](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})'
          })

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update and upgrade apt packages
      run: |
        sudo apt update

    - name: Install required apt packages
      run: |
        sudo apt install -y python3-pyqt5
        sudo apt install -y pyqt5-dev-tools
        sudo apt install -y qttools5-dev-tools

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run action.py for English UI
      run: python action.py en

    - name: Run action.py for Japanese UI
      run: python action.py ja

    - name: Rename builded_en.py to playblast_ffmpeg_en.py
      run: mv builded_en.py playblast_ffmpeg_en.py

    - name: Rename builded_ja.py to playblast_ffmpeg_ja.py
      run: mv builded_ja.py playblast_ffmpeg_ja.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset for English UI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: playblast_ffmpeg_en.py
        asset_name: playblast_ffmpeg_en.py
        asset_content_type: application/octet-stream

    - name: Upload Release Asset for Japanese UI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: playblast_ffmpeg_ja.py
        asset_name: playblast_ffmpeg_ja.py
        asset_content_type: application/octet-stream
